const removedUrls = [];
const newUrls = [];
const redirections = [];
const redirectSameRelease = [];

/* Note: new release versions must always be inserted in the first position of the array "versions" */
const versions = ["2.1"];

/* Data structure for every release

/* Pages changed within the same release */

/*
redirectSameRelease['x.y'] = {
  '/old/path/that/was/removed.html':
    'new/path/replacing/the/old/one.html',
  '/another-old/path/that/was/removed.html':
    'another-new/path/replacing/the/old/one.html',
};
*/

/* *** RELEASE X.Y ****/

/* Redirections from x.y-1 to x.y  */

/*
redirections.push(
    {
      'target': ['x.y-1=>x.y', 'x.y=>x.y-1'],
      'x.y-1': '/old-url',
      'x.y': '/new-url',
    }
);
*/

/* Pages added in x.y */

/*
newUrls['x.y'] = [
  '/new-url',
];
*/

/* Pages no longer available in x.y (this is not required if there is a redirection for this url) */

/*
removedUrls['x.y'] = [
  '/old-url',
];
*/

/* *** RELEASE 2.x *** */

/* Pages added in 2.x */

newUrls["2.1"] = [
  "/",
  "/index.html",
  "/search.html",
  "/release-notes/release_2_1.html",
  "/amazon/index.html",
  "/amazon/integration.html",
  "/amazon/use-cases/ec2.html",
  "/amazon/use-cases/iam.html",
  "/amazon/use-cases/",
  "/amazon/use-cases/vpc.html",
  "/deploying-with-ansible/consider.html",
  "/deploying-with-ansible/",
  "/deploying-with-ansible/install-ansible-control.html",
  "/deploying-with-ansible/reference.html",
  "/deploying-with-ansible/roles/",
  "/deploying-with-ansible/roles/armor-agent.html",
  "/deploying-with-ansible/roles/armor-elasticsearch.html",
  "/deploying-with-ansible/roles/armor-filebeat.html",
  "/deploying-with-ansible/roles/armor-kibana.html",
  "/deploying-with-ansible/roles/armor-logstash.html",
  "/deploying-with-ansible/roles/armor-manager.html",
  "/deploying-with-ansible/setup-remote-systems.html",
  "/deploying-with-puppet/",
  "/deploying-with-puppet/setup-puppet/",
  "/deploying-with-puppet/setup-puppet/install-puppet-agent.html",
  "/deploying-with-puppet/setup-puppet/install-puppet-master.html",
  "/deploying-with-puppet/setup-puppet/setup-puppet-certificates.html",
  "/deploying-with-puppet/armor-puppet-module/",
  "/deploying-with-puppet/armor-puppet-module/reference-armor-puppet/ossec-scanpaths.html",
  "/deploying-with-puppet/armor-puppet-module/reference-armor-puppet/armor-agent-class.html",
  "/deploying-with-puppet/armor-puppet-module/reference-armor-puppet/armor-server-class.html",
  "/development/client-keys.html",
  "/development/",
  "/development/message-format.html",
  "/docker/docker-installation.html",
  "/docker/faq-armor-container.html",
  "/docker/",
  "/docker/armor-container.html",
  "/getting-started/architecture.html",
  "/getting-started/components.html",
  "/getting-started/",
  "/getting-started/use-cases.html",
  "/getting-started/use-cases.html",
  "/installation-guide/",
  "/installation-guide/installing-elastic-stack/connect_armor_app.html",
  "/installation-guide/installing-elastic-stack/elastic_server_deb.html",
  "/installation-guide/installing-elastic-stack/elastic_server_rpm.html",
  "/installation-guide/installing-elastic-stack/",
  "/installation-guide/installing-armor-agent/",
  "/installation-guide/installing-armor-agent/armor_agent_deb.html",
  "/installation-guide/installing-armor-agent/armor_agent_macos.html",
  "/installation-guide/installing-armor-agent/armor_agent_rpm.html",
  "/installation-guide/installing-armor-agent/armor_agent_solaris.html",
  "/installation-guide/installing-armor-agent/armor_agent_sources.html",
  "/installation-guide/installing-armor-agent/armor_agent_windows.html",
  "/installation-guide/installing-armor-server/",
  "/installation-guide/installing-armor-server/sources_installation.html",
  "/installation-guide/installing-armor-server/armor_server_deb.html",
  "/installation-guide/installing-armor-server/armor_server_rpm.html",
  "/installation-guide/optional-configurations/elastic-tuning.html",
  "/installation-guide/optional-configurations/elastic_ssl.html",
  "/installation-guide/optional-configurations/",
  "/installation-guide/optional-configurations/kibana_ssl.html",
  "/installation-guide/optional-configurations/securing-api.html",
  "/installation-guide/packages-list/",
  "/installation-guide/unattended-installation.html",
  "/installation-guide/upgrading/",
  "/installation-guide/upgrading/legacy/",
  "/installation-guide/upgrading/legacy/upgrading-elastic-stack.html",
  "/installation-guide/upgrading/legacy/upgrading-armor-agent.html",
  "/installation-guide/upgrading/legacy/upgrading-armor-server.html",
  "/installation-guide/upgrading/same_major.html",
  "/installation-guide/upgrading/same_minor.html",
  "/installation-guide/virtual-machine.html",
  "/migrating-from-ossec/",
  "/migrating-from-ossec/ossec-packages-agent.html",
  "/migrating-from-ossec/ossec-packages-manager.html",
  "/not_found.html",
  "/pci-dss/active-response.html",
  "/pci-dss/elastic.html",
  "/pci-dss/file-integrity-monitoring.html",
  "/pci-dss/",
  "/pci-dss/log-analysis.html",
  "/pci-dss/policy-monitoring.html",
  "/pci-dss/rootkit-detection.html",
  "/release-notes/",
  "/user-manual/agents/agent-connection.html",
  "/user-manual/agents/command-line/",
  "/user-manual/agents/command-line/listing.html",
  "/user-manual/agents/command-line/register.html",
  "/user-manual/agents/command-line/remove.html",
  "/user-manual/agents/",
  "/user-manual/agents/restful-api/",
  "/user-manual/agents/restful-api/listing.html",
  "/user-manual/agents/restful-api/register.html",
  "/user-manual/agents/restful-api/remove.html",
  "/user-manual/agents/armor-app.html",
  "/user-manual/api/configuration.html",
  "/user-manual/api/examples.html",
  "/user-manual/api/getting-started.html",
  "/user-manual/api/",
  "/user-manual/api/reference.html",
  "/user-manual/capabilities/active-response/how-it-works.html",
  "/user-manual/capabilities/active-response/",
  "/user-manual/capabilities/active-response/remediation-configuration.html",
  "/user-manual/capabilities/active-response/remediation-faq.html",
  "/user-manual/capabilities/agentless-monitoring/agentless-configuration.html",
  "/user-manual/capabilities/agentless-monitoring/agentless-faq.html",
  "/user-manual/capabilities/agentless-monitoring/how-it-works.html",
  "/user-manual/capabilities/agentless-monitoring/",
  "/user-manual/capabilities/anomalies-detection/anomaly-configuration.html",
  "/user-manual/capabilities/anomalies-detection/anomaly-faq.html",
  "/user-manual/capabilities/anomalies-detection/how-it-works.html",
  "/user-manual/capabilities/anomalies-detection/",
  "/user-manual/capabilities/antiflooding.html",
  "/user-manual/capabilities/command-monitoring/command-configuration.html",
  "/user-manual/capabilities/command-monitoring/command-faq.html",
  "/user-manual/capabilities/command-monitoring/how-it-works.html",
  "/user-manual/capabilities/command-monitoring/",
  "/user-manual/capabilities/file-integrity/fim-configuration.html",
  "/user-manual/capabilities/file-integrity/fim-faq.html",
  "/user-manual/capabilities/file-integrity/how-it-works.html",
  "/user-manual/capabilities/file-integrity/",
  "/user-manual/capabilities/",
  "/user-manual/capabilities/labels.html",
  "/user-manual/capabilities/log-data-collection/how-it-works.html",
  "/user-manual/capabilities/log-data-collection/",
  "/user-manual/capabilities/log-data-collection/log-data-configuration.html",
  "/user-manual/capabilities/log-data-collection/log-data-faq.html",
  "/user-manual/capabilities/policy-monitoring/",
  "/user-manual/capabilities/policy-monitoring/openscap/how-it-works.html",
  "/user-manual/capabilities/policy-monitoring/openscap/",
  "/user-manual/capabilities/policy-monitoring/openscap/oscap-configuration.html",
  "/user-manual/capabilities/policy-monitoring/openscap/oscap-faq.html",
  "/user-manual/capabilities/policy-monitoring/rootcheck/how-it-works.html",
  "/user-manual/capabilities/policy-monitoring/rootcheck/",
  "/user-manual/capabilities/policy-monitoring/rootcheck/rootcheck-configuration.html",
  "/user-manual/capabilities/policy-monitoring/rootcheck/rootcheck-faq.html",
  "/user-manual/capabilities/system-calls-monitoring/audit-configuration.html",
  "/user-manual/capabilities/system-calls-monitoring/how-it-works.html",
  "/user-manual/capabilities/system-calls-monitoring/",
  "/user-manual/",
  "/user-manual/manager/alert-threshold.html",
  "/user-manual/manager/automatic-reports.html",
  "/user-manual/manager/",
  "/user-manual/manager/manual-email-report/",
  "/user-manual/manager/manual-email-report/smtp_authentication.html",
  "/user-manual/manager/manual-integration.html",
  "/user-manual/manager/manual-syslog-output.html",
  "/user-manual/manager/remote-service.html",
  "/user-manual/overview.html",
  "/user-manual/reference/centralized-configuration.html",
  "/user-manual/reference/daemons/",
  "/user-manual/reference/daemons/ossec-agentd.html",
  "/user-manual/reference/daemons/ossec-agentlessd.html",
  "/user-manual/reference/daemons/ossec-analysisd.html",
  "/user-manual/reference/daemons/ossec-authd.html",
  "/user-manual/reference/daemons/ossec-csyslogd.html",
  "/user-manual/reference/daemons/ossec-dbd.html",
  "/user-manual/reference/daemons/ossec-execd.html",
  "/user-manual/reference/daemons/ossec-logcollector.html",
  "/user-manual/reference/daemons/ossec-maild.html",
  "/user-manual/reference/daemons/ossec-monitord.html",
  "/user-manual/reference/daemons/ossec-remoted.html",
  "/user-manual/reference/daemons/ossec-reportd.html",
  "/user-manual/reference/daemons/ossec-syscheckd.html",
  "/user-manual/reference/daemons/armor-modulesd.html",
  "/user-manual/reference/",
  "/user-manual/reference/internal-options.html",
  "/user-manual/reference/ossec-conf/active-response.html",
  "/user-manual/reference/ossec-conf/agentless.html",
  "/user-manual/reference/ossec-conf/alerts.html",
  "/user-manual/reference/ossec-conf/auth.html",
  "/user-manual/reference/ossec-conf/client.html",
  "/user-manual/reference/ossec-conf/client_buffer.html",
  "/user-manual/reference/ossec-conf/commands.html",
  "/user-manual/reference/ossec-conf/database-output.html",
  "/user-manual/reference/ossec-conf/email_alerts.html",
  "/user-manual/reference/ossec-conf/global.html",
  "/user-manual/reference/ossec-conf/",
  "/user-manual/reference/ossec-conf/integration.html",
  "/user-manual/reference/ossec-conf/labels.html",
  "/user-manual/reference/ossec-conf/localfile.html",
  "/user-manual/reference/ossec-conf/logging.html",
  "/user-manual/reference/ossec-conf/remote.html",
  "/user-manual/reference/ossec-conf/reports.html",
  "/user-manual/reference/ossec-conf/rootcheck.html",
  "/user-manual/reference/ossec-conf/ruleset.html",
  "/user-manual/reference/ossec-conf/syscheck.html",
  "/user-manual/reference/ossec-conf/syslog-output.html",
  "/user-manual/reference/ossec-conf/verifying-configuration.html",
  "/user-manual/reference/ossec-conf/wodle-openscap.html",
  "/user-manual/reference/tools/agent-auth.html",
  "/user-manual/reference/tools/agent_control.html",
  "/user-manual/reference/tools/clear_stats.html",
  "/user-manual/reference/tools/",
  "/user-manual/reference/tools/manage_agents.html",
  "/user-manual/reference/tools/ossec-control.html",
  "/user-manual/reference/tools/ossec-logtest.html",
  "/user-manual/reference/tools/ossec-makelists.html",
  "/user-manual/reference/tools/ossec-regex.html",
  "/user-manual/reference/tools/rootcheck_control.html",
  "/user-manual/reference/tools/syscheck_control.html",
  "/user-manual/reference/tools/syscheck_update.html",
  "/user-manual/reference/tools/update-ruleset.py.html",
  "/user-manual/reference/tools/util.sh.html",
  "/user-manual/reference/tools/verify-agent-conf.html",
  "/user-manual/registering/",
  "/user-manual/registering/registration-process.html",
  "/user-manual/registering/use-registration-service.html",
  "/user-manual/ruleset/cdb-list.html",
  "/user-manual/ruleset/contribute.html",
  "/user-manual/ruleset/custom.html",
  "/user-manual/ruleset/dynamic-fields.html",
  "/user-manual/ruleset/getting-started.html",
  "/user-manual/ruleset/",
  "/user-manual/ruleset/ruleset-xml-syntax/decoders.html",
  "/user-manual/ruleset/ruleset-xml-syntax/",
  "/user-manual/ruleset/ruleset-xml-syntax/regex.html",
  "/user-manual/ruleset/ruleset-xml-syntax/rules.html",
  "/user-manual/ruleset/testing.html",
  "/user-manual/ruleset/update.html",
];
